In [7]:
import pandas as pd

In [9]:
data = pd.read_csv('disease_prediction.csv')

In [10]:
data

,patient_id,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
0,1,32,Male,101,235,152,79,28.5,73,No,Yes,Low,Yes,Yes
1,2,31,Male,124,191,134,77,33.9,71,No,Yes,Low,Yes,Yes
2,3,45,Male,57,141,114,71,27.2,79,Yes,Yes,Low,No,No
3,4,75,Female,69,268,120,82,21.5,61,Yes,Yes,Medium,No,Yes
4,5,53,Male,107,163,131,75,23.3,73,Yes,No,Low,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,24,Male,105,237,86,86,30.9,69,Yes,Yes,Medium,No,No
996,997,40,Male,120,219,133,72,34.3,92,Yes,Yes,Medium,No,No
997,998,44,Female,114,273,114,74,36.0,76,No,No,Low,No,Yes
998,999,31,Male,95,231,130,72,28.2,81,Yes,Yes,Medium,Yes,No
999,1000,83,Male,109,256,103,86,30.3,64,Yes,Yes,High,No,Yes

Performing Data Analysis

In [11]:
data.head()

,patient_id,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
0,1,32,Male,101,235,152,79,28.5,73,No,Yes,Low,Yes,Yes
1,2,31,Male,124,191,134,77,33.9,71,No,Yes,Low,Yes,Yes
2,3,45,Male,57,141,114,71,27.2,79,Yes,Yes,Low,No,No
3,4,75,Female,69,268,120,82,21.5,61,Yes,Yes,Medium,No,Yes
4,5,53,Male,107,163,131,75,23.3,73,Yes,No,Low,Yes,Yes

In [12]:
data.tail()

,patient_id,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
995,996,24,Male,105,237,86,86,30.9,69,Yes,Yes,Medium,No,No
996,997,40,Male,120,219,133,72,34.3,92,Yes,Yes,Medium,No,No
997,998,44,Female,114,273,114,74,36.0,76,No,No,Low,No,Yes
998,999,31,Male,95,231,130,72,28.2,81,Yes,Yes,Medium,Yes,No
999,1000,83,Male,109,256,103,86,30.3,64,Yes,Yes,High,No,Yes

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           1000 non-null   int64
 1   age                  1000 non-null   int64
 2   gender               1000 non-null   object
 3   glucose_mg_dl        1000 non-null   int64
 4   cholesterol_mg_dl    1000 non-null   int64
 5   systolic_bp          1000 non-null   int64
 6   diastolic_bp         1000 non-null   int64
 7   bmi                  1000 non-null   float64
 8   heart_rate           1000 non-null   int64
 9   smoking              1000 non-null   object
 10  alcohol_consumption  1000 non-null   object
 11  physical_activity    1000 non-null   object
 12  family_history       1000 non-null   object
 13  disease              1000 non-null   object
dtypes: float64(1), int64(7), object(6)
memory usage: 109.5+ KB

In [14]:
data.describe()

,patient_id,age,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,51.190000,104.163000,210.014000,123.893000,81.032000,26.093000,75.968000
std,288.819436,19.847514,25.076508,39.749111,18.701211,9.969974,4.758282,9.902982
min,1.000000,18.000000,30.000000,89.000000,67.000000,49.000000,16.000000,47.000000
25%,250.750000,33.000000,87.000000,183.000000,111.000000,74.000000,22.900000,70.000000
50%,500.500000,52.500000,105.000000,210.500000,124.000000,81.000000,26.000000,76.000000
75%,750.250000,69.000000,121.000000,235.250000,135.000000,88.000000,29.300000,83.000000
max,1000.000000,85.000000,184.000000,339.000000,195.000000,113.000000,41.500000,114.000000

In [16]:
data.shape

(1000, 14)

In [18]:
data.size

14000

In [19]:
data.columns

Index(['patient_id', 'age', 'gender', 'glucose_mg_dl', 'cholesterol_mg_dl',
       'systolic_bp', 'diastolic_bp', 'bmi', 'heart_rate', 'smoking',
       'alcohol_consumption', 'physical_activity', 'family_history',
       'disease'],
      dtype='object')

Checking Outlier

In [34]:
print(f"Min Age = {data['age'].min()}")
print(f"Max Age = {data['age'].max()}")

Min Age = 18
Max Age = 85

In [35]:
print(f"Min Glucose(mg/dl) = {data['glucose_mg_dl'].min()}")
print(f"Max Glucose(mg/dl) = {data['glucose_mg_dl'].max()}")

Min Glucose(mg/dl) = 30
Max Glucose(mg/dl) = 184

In [37]:
print(f"Min Cholesterol(mg/dl) = {data['cholesterol_mg_dl'].min()}")
print(f"Max Cholesterol(mg/dl) = {data['cholesterol_mg_dl'].max()}")

Min Cholesterol(mg/dl) = 89
Max Cholesterol(mg/dl) = 339

In [42]:
print(f"Min Systolic BP = {data['systolic_bp'].min()}")
print(f"Max Systolic BP = {data['systolic_bp'].max()}")

Min Systolic BP = 67
Max Systolic BP = 195

In [43]:
print(f"Min Diastolic BP = {data['diastolic_bp'].min()}")
print(f"Max Diastolic BP = {data['diastolic_bp'].max()}")

Min Diastolic BP = 49
Max Diastolic BP = 113

In [45]:
print(f"Min BMI = {data['bmi'].min()}")
print(f"Max BMI = {data['bmi'].max()}")

Min BMI = 16.0
Max BMI = 41.5

In [47]:
print(f"Min Heart Rate = {data['heart_rate'].min()}")
print(f"Max Heart Rate = {data['heart_rate'].max()}")

Min Heart Rate = 47
Max Heart Rate = 114