In [1]:
import pandas as pd

In [6]:
data = pd.read_csv("C:/Users/ADMIN/Heart_Disease_Prediction/Data/disease_prediction_cleaned.csv")

In [7]:
data

,patient_id,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
0,1,32,1,101,235,152,79,28.5,73,0,1,1,1,1
1,2,31,1,124,191,134,77,33.9,71,0,1,1,1,1
2,3,45,1,57,141,114,71,27.2,79,1,1,1,0,0
3,4,75,0,69,268,120,82,21.5,61,1,1,2,0,1
4,5,53,1,107,163,131,75,23.3,73,1,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,996,24,1,105,237,86,86,30.9,69,1,1,2,0,0
995,997,40,1,120,219,133,72,34.3,92,1,1,2,0,0
996,998,44,0,114,273,114,74,36.0,76,0,0,1,0,1
997,999,31,1,95,231,130,72,28.2,81,1,1,2,1,0
998,1000,83,1,109,256,103,86,30.3,64,1,1,0,0,1

In [8]:
data[data['glucose_mg_dl'] == 30]

Empty DataFrame
Columns: [patient_id, age, gender, glucose_mg_dl, cholesterol_mg_dl, systolic_bp, diastolic_bp, bmi, heart_rate, smoking, alcohol_consumption, physical_activity, family_history, disease]
Index: []

In [9]:
data.head()

,patient_id,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
0,1,32,1,101,235,152,79,28.5,73,0,1,1,1,1
1,2,31,1,124,191,134,77,33.9,71,0,1,1,1,1
2,3,45,1,57,141,114,71,27.2,79,1,1,1,0,0
3,4,75,0,69,268,120,82,21.5,61,1,1,2,0,1
4,5,53,1,107,163,131,75,23.3,73,1,0,1,1,1

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           999 non-null    int64
 1   age                  999 non-null    int64
 2   gender               999 non-null    int64
 3   glucose_mg_dl        999 non-null    int64
 4   cholesterol_mg_dl    999 non-null    int64
 5   systolic_bp          999 non-null    int64
 6   diastolic_bp         999 non-null    int64
 7   bmi                  999 non-null    float64
 8   heart_rate           999 non-null    int64
 9   smoking              999 non-null    int64
 10  alcohol_consumption  999 non-null    int64
 11  physical_activity    999 non-null    int64
 12  family_history       999 non-null    int64
 13  disease              999 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 109.4 KB

In [11]:
data['pulse_pressure'] = (
    data['systolic_bp'] - data['diastolic_bp'])

In [12]:
data[['systolic_bp', 'diastolic_bp', 'pulse_pressure']].head()

   systolic_bp  diastolic_bp  pulse_pressure
0          152            79              73
1          134            77              57
2          114            71              43
3          120            82              38
4          131            75              56

In [15]:
data['bmi_category'] = pd.cut(
    data['bmi'],
    bins=[0, 18.5, 25, 30, 100],
    labels=['underweight', 'normal', 'overweight', 'obese']
)

TypeError: '<' not supported between instances of 'float' and 'str'

In [25]:
data[['bmi','disease']]

            bmi  disease
0    overweight        1
1         obese        1
2    overweight        0
3        normal        1
4        normal        1
..          ...      ...
994       obese        0
995       obese        0
996       obese        1
997  overweight        0
998       obese        1

[999 rows x 2 columns]